FROM       hongchhe/ubuntu-python3
MAINTAINER hehongchuang@gmail.com

ENV        SCALA_VERSION 2.12
ENV        KAFKA_VERSION 2.1.1
ENV        KAFKA_HOME /opt/kafka
ENV        REPO_BASE http://mirrors.hust.edu.cn/apache/kafka
ENV        KAFKA_CONFIG_DIR=${KAFKA_HOME}/config

RUN        apt-get install -y openjdk-8-jdk \
        && mkdir -p ${KAFKA_HOME} \
        && curl ${REPO_BASE}/${KAFKA_VERSION}/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz | tar -xzC ${KAFKA_HOME} --strip-components=1 \
        && curl https://bootstrap.pypa.io/get-pip.py | python3 \
        && pip install kafka-python

COPY       config/server.properties ${KAFKA_CONFIG_DIR}/server.properties
COPY       run.sh /tmp

RUN        chmod 755 /tmp/run.sh \
        && groupadd -r kafka \
        && useradd --comment "Kafka Daemon User" --shell /bin/bash -M -r -g kafka --home ${KAFKA_HOME} kafka \
        && chown -R kafka:kafka ${KAFKA_HOME}

EXPOSE     2181 9092 9093 8888

WORKDIR    ${KAFKA_HOME}

ENTRYPOINT ["/tmp/run.sh"]